// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(target) {
    var key, output, value, _i, _ref, _results;
    output = {};
    for (key = _i = 0, _ref = target.length; 0 <= _ref ? _i < _ref : _i > _ref; key = 0 <= _ref ? ++_i : --_i) {
      output[target[key]] = target[key];
    }
    _results = [];
    for (key in output) {
      value = output[key];
      _results.push(value);
    }
    return _results;
  };

}).call(this);
