// Generated by CoffeeScript 1.8.0
(function() {
  var winston;

  winston = require('winston');

  module.exports = {
    log: function(err, req, res, next) {
      err.location = err.stack.split('\n')[1];
      err.url = req.originalUrl;
      winston.error(JSON.stringify(err, ['message', 'url', 'inner', 'location']));
      return next(err);
    },
    xhr: function(err, req, res, next) {
      if (req.xhr) {
        return res.status(500).send({
          error: "Something blew up!"
        });
      }
      return next(err);
    },
    "default": function(err, req, res, next) {
      res.status(500);
      return res.send("<h1>Oops!</h1><div>" + err.message + "</div>");
    }
  };

}).call(this);
