// Generated by CoffeeScript 1.8.0
(function() {
  var request, router;

  router = require('express').Router();

  request = require('request');

  router.get('/product', function(req, res, next) {
    return app.json({
      id: 1,
      name: 'product-1'
    });
  });

  module.exports = router;

}).call(this);
