// Generated by CoffeeScript 1.8.0
(function() {
  var app, bodyParser, errorService, express, port, winston;

  require('dotenv').load();

  express = require('express');

  bodyParser = require('body-parser');

  winston = require('winston');

  errorService = require('./ErrorService');

  app = express();

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(bodyParser.json());

  app.use('/ware', [require('./SynonymRoutes')]);

  app.use(errorService.log);

  app.use(errorService.xhr);

  app.use(errorService["default"]);

  port = process.env.PORT || 3000;

  app.listen(port, function() {
    return winston.info("ware-house API [" + process.env.NODE_ENV + "] is listening on port " + port);
  });

}).call(this);
