// Generated by CoffeeScript 1.8.0
(function() {
  var dedupe, request, router;

  router = require('express').Router();

  request = require('request');

  dedupe = require('./deduplicate');

  router.get('/synonym', function(req, res, next) {
    var url;
    url = "" + process.env.SYNONYM_API_URL + "/?word=" + req.query.word + "&language=en_US&output=json&key=" + process.env.SYNONYM_API_KEY;
    return request.get(url, function(err, response, json) {
      var item, synonym, synonyms, _i, _j, _len, _len1, _ref;
      if (err != null) {
        return next(err);
      }
      response = JSON.parse(json).response;
      synonyms = [];
      for (_i = 0, _len = response.length; _i < _len; _i++) {
        item = response[_i];
        _ref = item.list.synonyms.split('|');
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          synonym = _ref[_j];
          if (!(synonym.indexOf('(antonym)') === -1)) {
            continue;
          }
          synonym = synonym.replace('(related term)', '').replace('(similar term)', '').trim();
          synonyms.push(synonym);
        }
      }
      return res.json(dedupe(synonyms.sort()));
    });
  });

  module.exports = router;

}).call(this);
